version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: collabnote_postgres
    environment:
      POSTGRES_DB: collabnote_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
